[package]
name = "isal-sys"
version = "0.2.0"
edition = "2021"
authors = ["Atelier Icicle <i@icyf.me>"]
description = "Rust bindings for Intel ISA-L"
license = "MIT"

build = "build.rs"
links = "isal"

[build-dependencies]
pkg-config = "0.3"
autotools = "0.2"
